CC=g++
OFILES1 = chisq.o bioplib/OpenStdFiles.o
OFILES2 = chisig.o
OFILES3 = chisq3.o bioplib/OpenStdFiles.o


all : chisq chisig


chisq : $(OFILES1)
	$(CC) -o $@ $(OFILES1) -lm
chisq3 : $(OFILES3)
	$(CC) -o $@ $(OFILES3) -lm
chisig : $(OFILES2)
	(cd numerics; make)
	$(CC) -Lnumerics -o $@ $(OFILES2) -lnumerics -lm
.c.o :
	$(CC) -c -o $@ $<

clean :
	\rm -f $(OFILES1) $(OFILES2) $(OFILES3)
	(cd numerics; make clean)

